<a href="https://colab.research.google.com/github/hannaginther/ENGG680_2025_Fall/blob/Hanna/Project/Group_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ENGG680 - Introduction to Digital Engineering**
## *Group Project: Implementing ML model for Hospital Length of Stay Prediction*

## Preliminary: Certificate of Work
### (5 Marks)

*We, the undersigned, certify that this is our own work, which has been done expressly for this course, either without the assistance of any other party or where appropriate we have acknowledged the work of others. Further, we have read and understood the section in the university calendar on plagiarism/cheating/other academic misconduct and we are aware of the implications thereof. We request that the total mark for this assignment be distributed as follows among group members:*

|          | First Name | Last Name | Signature (Full Name, Date) | Hours | Contribution % |
|----------|------------|-----------|-----------------------------|-------|----------------|
| Member 1: | Allison | Haynes | Signature, Date | hrs | 33.33% |
| Member 2: | Diya | Chakraborty | Signature, Date | hrs | 33.33% |
| Member 3: | Hanna | Ginther | Signature, Date | hrs | 33.33% |

##**Step #1: Data Cleaning & Preprocessing:**

In [1]:
#TESTING FETCHING MAIN TO HANNA
print ('This is a test!')

This is a test!

##**Import Libraries and Load Datasets**

In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

In [24]:
sparcs_2024 = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2024_20251029.csv')

/tmp/ipython-input-841084618.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  sparcs_2024 = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2024_20251029.csv')

In [25]:
sparcs_2023 = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2023_20251029.csv')

/tmp/ipython-input-1854978552.py:1: DtypeWarning: Columns (29) have mixed types. Specify dtype option on import or set low_memory=False.
  sparcs_2023 = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2023_20251029.csv')

##**Inspect Data Structure and Check Missing Values**

In [ ]:
sparcs_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2125754 entries, 0 to 2125753
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 535.2+ MB

In [ ]:
sparcs_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2196737 entries, 0 to 2196736
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code                             object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        float64
 32  Total Costs                          float64
dtypes: float64(4), int64(4), object(25)
memory usage: 553.1+ MB

In [ ]:
sparcs_2023.head()

,Hospital Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code - 3 digits,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,New York City,Bronx,7000006.0,3058.0,Montefiore Med Center - Jack D Weiler Hosp of ...,50 to 69,104,F,Other Race,Spanish/Hispanic,...,Moderate,Moderate,Medical,Medicaid,NaN,NaN,NaN,Y,"27,380.60","3,533.21"
1,New York City,Bronx,7000006.0,1168.0,Montefiore Medical Center-Wakefield Hospital,30 to 49,104,M,Black/African American,Not Span/Hispanic,...,Moderate,Minor,Medical,Medicaid,NaN,NaN,NaN,Y,"82,629.98","12,715.35"
2,New York City,Bronx,7000006.0,3058.0,Montefiore Med Center - Jack D Weiler Hosp of ...,50 to 69,104,M,Other Race,Not Span/Hispanic,...,Extreme,Extreme,Medical,Medicare,Medicaid,NaN,NaN,Y,"76,210.47","11,201.40"
3,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,18 to 29,104,M,Black/African American,Not Span/Hispanic,...,Moderate,Minor,Medical,Medicaid,NaN,NaN,NaN,Y,"77,532.60","13,872.77"
4,New York City,Bronx,7000006.0,1169.0,Montefiore Medical Center - Henry & Lucy Moses...,50 to 69,104,F,Other Race,Spanish/Hispanic,...,Major,Moderate,Medical,Medicare,Medicaid,NaN,NaN,Y,"63,430.29","10,249.28"

In [ ]:
sparcs_2024.head()

,Health Service Area,Hospital County,Operating Certificate Number,Permanent Facility Id,Facility Name,Age Group,Zip Code,Gender,Race,Ethnicity,...,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Birth Weight,Emergency Department Indicator,Total Charges,Total Costs
0,Hudson Valley,Westchester,5957001.0,1139.0,WESTCHESTER MEDICAL CENTER,0-17,OOS,F,White,Not Span/Hispanic,...,Moderate,Minor,Medical,Private Health Insurance,NaN,NaN,NaN,Y,46814.00,6772.07
1,New York City,Queens,7003001.0,1628.0,FLUSHING HOSPITAL MEDICAL CENTER,0-17,113,M,White,Spanish/Hispanic,...,Moderate,Moderate,Medical,Medicaid,NaN,NaN,NaN,Y,13490.00,15464.30
2,New York City,New York,7002054.0,1458.0,NEW YORK-PRESBYTERIAN HOSPITAL - NEW YORK WEIL...,70 or Older,100,M,White,Not Span/Hispanic,...,Moderate,Moderate,Medical,Medicare,Private Health Insurance,NaN,NaN,Y,49503.16,9324.77
3,New York City,New York,7002054.0,1464.0,NEW YORK-PRESBYTERIAN HOSPITAL - COLUMBIA PRES...,0-17,100,F,Other Race,Not Span/Hispanic,...,Minor,Minor,Medical,Private Health Insurance,NaN,NaN,2700,Y,27827.66,7304.27
4,New York City,New York,7002032.0,1466.0,MOUNT SINAI WEST,18-29,100,F,Other Race,Spanish/Hispanic,...,Moderate,Minor,Medical,Medicare,NaN,NaN,NaN,Y,32798.29,7948.10

##**Dropping Unnecessary Columns, Matching 2023 Column Names to 2024, Changing Dtypes to Prep for Merging DataFrames**

In [26]:
# Drop hospital costs, emergency indicator, birth weight from both dataframes
sparcs_2023.drop(columns=['Total Costs', 'Emergency Department Indicator', 'Birth Weight', 'Operating Certificate Number'], inplace=True)
sparcs_2024.drop(columns=['Total Costs', 'Emergency Department Indicator', 'Birth Weight', 'Operating Certificate Number'], inplace=True)

In [27]:
# Change column names in sparcs_2023 to match 2024 DataFrame:
sparcs_2023.rename(columns={
    'Hospital Service Area':'Health Service Area',
    'Zip Code - 3 digits':'Zip Code'
}, inplace=True)

In [28]:
# Change dtype of charges column in sparcs_2023 to float64:
sparcs_2023['Total Charges'] = (sparcs_2023['Total Charges'].replace(',', '', regex=True).astype('float64'))

##**Compare Code/Description Columns and Facility ID/Name Columns to find matches between datasets**

In [ ]:
# Identify code/description columns
code_cols = [
    'CCSR Diagnosis Code',
    'CCSR Procedure Code',
    'APR DRG Code',
    'APR MDC Code'
]

desc_cols = [
    'CCSR Diagnosis Description',
    'CCSR Procedure Description',
    'APR DRG Description',
    'APR MDC Description'
]

# Pair code/desc columns
code_columns = list(zip(code_cols, desc_cols))

# Normalize description columns in sparcs_2023
for _, desc_col in code_columns:
  if desc_col in sparcs_2023.columns:
    sparcs_2023[desc_col] = sparcs_2023[desc_col].apply(
        lambda x: x.upper().replace('&', 'AND') if isinstance(x, str) else x
        )

# Compare datasets
comparison_codes_results = {}
for code_col, desc_col in code_columns:
  df_2023 = sparcs_2023[[code_col, desc_col]].drop_duplicates()
  df_2024 = sparcs_2024[[code_col, desc_col]].drop_duplicates()

  merged = df_2023.merge(df_2024, on=code_col, how='outer', suffixes=('_2023', '_2024'))

  # Add indicator for where code appears
  merged['_status_'] = merged.apply(
      lambda row: (
          'Only in 2023' if pd.isna(row[desc_col + '_2024']) else
          'Only in 2024' if pd.isna(row[desc_col + '_2023']) else
          'Description mismatch' if row[desc_col + '_2023'] != row[desc_col + '_2024'] else
          'Match'
      ),
      axis=1
    )

  comparison_codes_results[code_col] = merged

# Combine comparisons
combined_codes_results = pd.concat(
    [df.assign(Column_Compared=col) for col, df in comparison_codes_results.items()],
    ignore_index=True
)

# Select columns that exist for code/desc
all_cols = ['Column_Compared', '_status_']
for code_col, desc_col in code_columns:
  for col in [code_col, desc_col + '_2023', desc_col + '_2024']:
    if col in combined_codes_results.columns:
      all_cols.append(col)

combined__codes_results = combined_codes_results[all_cols]

# Save to CSV
combined__codes_results.to_csv('/content/sparcs_codes_comparison.csv', index=False)
print("Comparison results saved to /content/sparcs_codes_comparison.csv")

In [ ]:
# Get column info related to facility id/name
facility_id = ['Permanent Facility Id']
facility_name = ['Facility Name']

facility_columns = list(zip(facility_id, facility_name))

# Normalize facility column for sparcs_2023
for _, facility_name in facility_columns:
  if facility_name in sparcs_2023.columns:
    sparcs_2023[facility_name] = sparcs_2023[facility_name].apply(
        lambda x: x.upper() if isinstance(x, str) else x
    )
# Compare datasets
comparison_facility_results = {}
for facility_id, facility_name in facility_columns:
  df_2023 = sparcs_2023[[facility_id, facility_name]].drop_duplicates()
  df_2024 = sparcs_2024[[facility_id, facility_name]].drop_duplicates()

  merged = df_2023.merge(df_2024, on=facility_id, how='outer', suffixes=('_2023', '_2024'))

  merged['_status_'] = merged.apply(
      lambda row: (
          'Only in 2023' if pd.isna(row[facility_name + '_2024']) else
          'Only in 2024' if pd.isna(row[facility_name + '_2023']) else
          'Name mismatch' if row[facility_name + '_2023'] != row[facility_name + '_2024'] else
          'Match'
      ),
      axis=1
    )
  comparison_facility_results[facility_id] = merged

  # Combine comparisons
  combined_facility_results = pd.concat(
      [df.assign(Column_Compared=col) for col, df in comparison_facility_results.items()],
      ignore_index=True
  )

  # Select columns that exist for facility ID/Name
  all_facility_cols = ['Column_Compared', '_status_']
  for facility_id, facility_name in facility_columns:
    for col in [facility_id, facility_name + '_2023', facility_name + '_2024']:
      if col in combined_facility_results.columns:
        all_facility_cols.append(col)

  combined_facility_results = combined_facility_results[all_facility_cols]

Comparison results saved to /content/sparcs_facilities_comparison.csv

##**Develop a Fuzzy Matching Function to Search for Similar, but Differently Reported Values**

In [ ]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 31.9 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.3

In [ ]:
# Normalize facility column capitalization for sparcs_2023
for facility_name in ['Facility Name']:
  if facility_name in sparcs_2023.columns:
    sparcs_2023[facility_name] = sparcs_2023[facility_name].apply(
        lambda x: x.upper() if isinstance(x, str) else x
    )

# Normalize CCSR Diagnosis Description capitalization for sparcds_2023
for ccsr_desc in ['CCSR Diagnosis Description']:
  if ccsr_desc in sparcs_2023:
    sparcs_2023[ccsr_desc] = sparcs_2023[ccsr_desc].apply(
        lambda x: x.upper() if isinstance(x, str) else x
    )

In [ ]:
# Replace all uses of ampersand in sparcs_2023 with 'AND' except for facility name
for and_val in sparcs_2023:
  if and_val not in ['Facility Name']:
    sparcs_2023[and_val] = sparcs_2023[and_val].apply(
        lambda x: x.replace('&', 'AND') if isinstance(x, str) else x
    )

In [ ]:
# Define a function to preprocess strings for fuzzy matching
# STEP 1: convert all object dtypes to strings except for specified columns
excluded_columns = ['Zip Code', 'Length of Stay', 'CCSR Diagnosis Code', 'CCSR Procedure Code']

# Get Object Columns except for excluded ones
convert_columns_2023 = [col for col in sparcs_2023.select_dtypes('object').columns if col not in excluded_columns]
convert_columns_2024 = [col for col in sparcs_2024.select_dtypes('object').columns if col not in excluded_columns]

sparcs_2023 = sparcs_2023.astype({col: 'string' for col in convert_columns_2023})
sparcs_2024 = sparcs_2024.astype({col: 'string' for col in convert_columns_2024})

# Convert selected object columns to string

# STEP 2: preprocessing function:
def clean_string(s):
  """
  Lowercase, remove punctuation, normalize whitespace.
  """
  if pd.isna(s):
    return(s)
  s = str(s).lower()                    # lowercase
  s = re.sub(r'[^\w\s]', '', s)         # remove punctuation
  s = re.sub(r'\s+', ' ', s)            # normalize whitespace
  return s.strip()

In [ ]:
import re
from rapidfuzz import process, fuzz

# Def fuzzy matching function for all object columns:
def fuzzy_match_all_columns (df1, df2, object_columns, threshold=50, scorer=fuzz.ratio):
  """
  Perform a fuzzy matching function between df1 and df2 across all object/string columns

  Parameters
  ----------
  - df1, df2 : pd.DataFrame
      DataFrames to compare
  - object_columns : list
      Columns in DataFrame to compare (targets)
  - threshold : int, optional
      Minimum similarity score (0-100) for inclusion
  - scorer : function
      Fuzzy scoring function (default = fuzz.ratio)

  Returns
  -------
  pd.DataFrame
    DataFrame with matches and similarity scores >= threshold
  """

  # STEP 1: Identify
  all_matches = []
  for col in object_columns:
    print(f"Processing column: {col}")

    # Unique Values
    vals_2023 = df1[col].dropna().unique()
    vals_2024 = df2[col].dropna().unique()

    # Skip if either dataset has no values for this column
    if len(vals_2023) == 0 or len(vals_2024) == 0:
        print(f"  Skipping column '{col}' (no values to match)")
        continue

    # Call clean_string function to preprocess 2024 values
    preprocessed_2024 = {v: clean_string(v) for v in vals_2024}

    for v in vals_2023:
      clean_v = clean_string(v)
      best_match = process.extractOne(
          clean_v,
          preprocessed_2024.values(),
          scorer=scorer
      )
      if best_match:
        matched_val, score, _ = best_match
        if score >= threshold:
          # Recover original 2024 string:
          original_2024 = next(k for k, val in preprocessed_2024.items() if val == matched_val)
          all_matches.append({
              'Column': col,
              '2023_value': v,
              '2024_best_match': original_2024,
              'Similarity_Score': score
          })
  if all_matches:
        return pd.DataFrame(all_matches)
  else:
        print("No matches found above the threshold.")
        return pd.DataFrame(columns=['Column', '2023_value', '2024_best_match', 'Similarity_Score'])

  return pd.DataFrame(all_matches)

In [ ]:
# Fuzzy Match function usage:
object_cols = [
    'Health Service Area',
    'Hospital County',
    'Facility Name',
    'Age Group',
    'Gender',
    'Race',
    'Ethnicity',
    'Type of Admission',
    'Patient Disposition',
    'CCSR Diagnosis Description',
    'CCSR Procedure Description',
    'APR DRG Description',
    'APR MDC Description',
    'APR Severity of Illness Description',
    'APR Risk of Mortality',
    'APR Medical Surgical Description',
    'Payment Typology 1',
    'Payment Typology 2',
    'Payment Typology 3'
]

# Run full fuzzy matching
all_matches_df = fuzzy_match_all_columns(
    sparcs_2023,
    sparcs_2024,
    object_cols,
    threshold=50,
)

Processing column: Health Service Area
Processing column: Hospital County
Processing column: Facility Name
Processing column: Age Group
Processing column: Gender
Processing column: Race
Processing column: Ethnicity
Processing column: Type of Admission
Processing column: Patient Disposition
Processing column: CCSR Diagnosis Description
Processing column: CCSR Procedure Description
Processing column: APR DRG Description
Processing column: APR MDC Description
Processing column: APR Severity of Illness Description
Processing column: APR Risk of Mortality
Processing column: APR Medical Surgical Description
Processing column: Payment Typology 1
Processing column: Payment Typology 2
Processing column: Payment Typology 3

In [ ]:
all_matches_df.head()

                Column     2023_value 2024_best_match  Similarity_Score
0  Health Service Area  New York City   New York City             100.0
1  Health Service Area  Hudson Valley   Hudson Valley             100.0
2  Health Service Area     Western NY      Western NY             100.0
3  Health Service Area   Finger Lakes    Finger Lakes             100.0
4  Health Service Area     Central NY      Central NY             100.0

In [ ]:
# Get CSV of fuzzy matches:
all_matches_df.to_csv('/content/sparcs_fuzzy_match_review.csv', index=False)

##**Create a Harmonization Function Before Combining Sparcs_2023 and 2024**

In [ ]:
# Defining Harmonization Function to correct sparcs_2023 values

def harmonize_categorical(
    df_2023,
    fuzzy_matches_df,
    similarity_threshold=90,
    manual_2024_to_2023=None,
    protected_cols=None,
    protected_values=None):

  """
  Harmonize categorical columns in df_2023 using fuzzy match results with 2024 as reference.

  Parameters:
  - df_2023: DataFrame for 2023
  - fuzzy_matches_df: DataFrame with ['Column', '2023_value', '2024_best_match', 'Similarity_Score']
  - similarity_threshold: float, minimum similarity to apply automatic harmonization
  - manual_2024_to_2023: dict of dicts for 2024->2023 overrides, e.g.,
      {'Column1': {'2024_val': '2023_val'}}
  - protected_cols: list of columns to skip completely (won't be harmonized)
  - protected_values: list of values to skip completely (won't be harmonized)

  Returns:
  - Harmonized df_2023
  """

  if protected_cols is None:
    protected_cols = []

  # Initialize harmonized DataFrame
  df_harmonized = df_2023.copy()

  # Ensure similarity score is numeric
  fuzzy_matches_df['Similarity_Score'] = pd.to_numeric(
      fuzzy_matches_df['Similarity_Score'], errors='coerce'
      )

  # Step 1: Harmonize based on fuzzy matches above threshold
  for col in fuzzy_matches_df['Column'].unique():
    if col in protected_cols or col not in df_harmonized.columns:
      continue    # skip protected or missing cols

    col_matches = fuzzy_matches_df[
        (fuzzy_matches_df['Column'] == col)
        & (fuzzy_matches_df['Similarity_Score'] >= similarity_threshold)
    ]

    if col_matches.empty:
      continue  # skip if no matches above threshold

    mapping_dict = dict(zip(col_matches['2023_value'], col_matches['2024_best_match']))

    protected_vals = protected_values.get(col, [] if protected_values else [])

    # Apply mapping (Preserve NaN and protected values)
    df_harmonized[col] = df_harmonized[col].apply(
        lambda x: mapping_dict.get(x, x)
        if pd.notna(x) and x not in protected_values
        else x
    )

  # Step 2: Apply manual overrides (2024 -> 2023; values below threshold)
  if manual_2024_to_2023:
    for col, overrides in manual_2024_to_2023.items():
      if col in df_harmonized.columns:
        df_harmonized[col] = df_harmonized[col].apply(
            lambda x: overrides.get(x, x) if pd.notna(x) else x
            )

  return df_harmonized

In [ ]:
# Harmonization function usage:
sparcs_2023_harmonized = harmonize_categorical(
    df_2023 = sparcs_2023,
    fuzzy_matches_df = all_matches_df,
    similarity_threshold = 90,
    manual_2024_to_2023 = {
    "APR MDC Description": {
        "INJURIES, POISONINGS & TOXIC EFFECTS OF DRUGS": "POISONINGS, TOXIC EFFECTS OTHER INJURIES AND OTHER COMPLICATIONS OF TREATMENT",
        "FACTORS INFLUENCING HLTH STAT & OTHR CONTACTS WITH HLTH SERVCS": "REHABILITATION AFTERCARE OTHER FACTORS INFLUENCING HEALTH STATUS AND OTHER HEALTH SERVICE CONTACTS"
    },
    "Age Group": {
        "0 to 17": "0-17",
        "18 to 29": "18-29",
        "30 to 49": "30-49",
        "50 to 69": "50-69"
    },
    "Facility Name": {
        "NYC Health + Hospitals/South Brooklyn Health": "SOUTH BROOKLYN HEALTH"
    },
    "APR DRG Description": {
        "OTHER EAR, NOSE, MOUTH AND THROAT PROCEDURES": "OTHER EAR, NOSE, MOUTH, THROAT, CRANIOFACIAL, AND NECK PROCEDURES"
    },
    "Health Service Area": {
        "Capital/Adirond": "Capital/Adirondacks"
    },
    "Hospital County": {
        "St Lawrence": "Saint Lawrence"
    }
},
    protected_cols = [
        "Length of Stay",
        "Zip Code",
        "Permanent Facility Id",
        "Race",
        "Ethnicity",
        "APR MDC Code",
        "APR Severity of Illness Code",
        "APR Severity of Illness Description",
        "APR Risk of Mortality",
        "APR Medical Surgical Description",
        "Payment Typology 1",
        "Payment Typology 2",
        "Payment Typology 3"
        ],
    protected_values = {
        "APR MDC Description": ["DISEASES AND DISORDERS OF BLOOD, BLOOD FORMING ORGANS, IMMUNOLOG DISORD"]
    }
)

In [ ]:
# Get CSV of harmonized sparcs_2023
sparcs_2023_harmonized.to_csv('/content/sparcs_2023_harmonized.csv', index=False)

In [ ]:
sparcs_2023_harmonized.head()

,Health Service Area,Hospital County,Permanent Facility Id,Facility Name,Age Group,Zip Code,Gender,Race,Ethnicity,Length of Stay,...,APR MDC Code,APR MDC Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Payment Typology 1,Payment Typology 2,Payment Typology 3,Total Charges
0,New York City,Bronx,3058.0,MONTEFIORE MED CENTER - JACK D WEILER HOSP OF ...,50-69,104,F,Other Race,Spanish/Hispanic,1,...,23,FACTORS INFLUENCING HLTH STAT AND OTHR CONTACT...,2,Moderate,Moderate,Medical,Medicaid,<NA>,<NA>,27380.60
1,New York City,Bronx,1168.0,MONTEFIORE MEDICAL CENTER-WAKEFIELD HOSPITAL,30-49,104,M,Black/African American,Not Span/Hispanic,4,...,4,DISEASES AND DISORDERS OF THE RESPIRATORY SYSTEM,2,Moderate,Minor,Medical,Medicaid,<NA>,<NA>,82629.98
2,New York City,Bronx,3058.0,MONTEFIORE MED CENTER - JACK D WEILER HOSP OF ...,50-69,104,M,Other Race,Not Span/Hispanic,4,...,18,"INFECTIOUS AND PARASITIC DISEASES, SYSTEMIC OR...",4,Extreme,Extreme,Medical,Medicare,Medicaid,<NA>,76210.47
3,New York City,Bronx,1169.0,MONTEFIORE MEDICAL CENTER - HENRY & LUCY MOSES...,18-29,104,M,Black/African American,Not Span/Hispanic,5,...,16,"DISEASES AND DISORDERS OF BLOOD, BLOOD FORMING...",2,Moderate,Minor,Medical,Medicaid,<NA>,<NA>,77532.60
4,New York City,Bronx,1169.0,MONTEFIORE MEDICAL CENTER - HENRY & LUCY MOSES...,50-69,104,F,Other Race,Spanish/Hispanic,3,...,18,"INFECTIOUS AND PARASITIC DISEASES, SYSTEMIC OR...",3,Major,Moderate,Medical,Medicare,Medicaid,<NA>,63430.29

In [ ]:
changed_cols = []
for col in sparcs_2023.columns:
  if not sparcs_2023[col].equals(sparcs_2023_harmonized[col]):
    changed_cols.append(col)

print("Columns modified during harmonization: ", changed_cols)

Columns modified during harmonization:  ['Health Service Area', 'Hospital County', 'Facility Name', 'Age Group', 'APR DRG Description', 'APR MDC Description', 'Payment Typology 3']

In [ ]:
# Apply manual corrections to sparcs_2024 - These are values in the 2024 DataFrame that lacked commas or clarity, or were spelled incorrectly
manual_corrections = {
    "Facility Name": {
        "COHEN'S CHILDREN MEDICAL CENTER W/LIJ": "COHEN CHILDREN'S MEDICAL CENTER"
    },
    "CCSR Diagnosis Description": {
        "CORONAVIRUS DISEASE 2019 (COVID-19)": "COVID-19"
    },
    "APR MDC Code": {
        "DISEASES AND DISORDERS OF THE SKIN SUBCUTANEOUS TISSUE AND BREAST":
          "DISEASES AND DISORDERS OF THE SKIN, SUBCUTANEOUS TISSUE AND BREAST",
        "ENDOCRINE NUTRITIONAL AND METABOLIC DISEASES AND DISORDERS":
          "ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES AND DISORDERS",
        "DISEASES AND DISORDERS OF BLOOD BLOOD FORMING ORGANS AND IMMUNOLOG DISORD":
          "DISEASES AND DISORDERS OF BLOOD, BLOOD FORMING ORGANS AND IMMUNOLOG DISORD"
    }
}

# Create a harmonized copy of sparcs_2024 for merging:
sparcs_2024_harmonized = sparcs_2024.copy()

# Input corrections
for col, mapping in manual_corrections.items():
  sparcs_2024_harmonized[col] = sparcs_2024_harmonized[col].replace(mapping)

##**Combine sparcs_2023 and sparcs_2024 into One DataFrame**

In [ ]:
# Keep track of source year from each DataFrame w/new column:
sparcs_2023_harmonized['Year'] = 2023
sparcs_2024_harmonized['Year'] = 2024

# Combine DataFrames
sparcs_combined = pd.concat(
    [sparcs_2023_harmonized, sparcs_2024_harmonized],
    axis=0,
    ignore_index=True
)

In [ ]:
# Get CSV of combined dataframe
sparcs_combined.to_csv('/content/sparcs_combined.csv', index=False)

##**Preprocess Combined DataFrame**

In [ ]:
# Load DataFrame
sparcs_combined = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/sparcs_combined.csv')

In [ ]:
sparcs_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4322491 entries, 0 to 4322490
Data columns (total 30 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Health Service Area                  object
 1   Hospital County                      object
 2   Permanent Facility Id                float64
 3   Facility Name                        object
 4   Age Group                            object
 5   Zip Code                             object
 6   Gender                               object
 7   Race                                 object
 8   Ethnicity                            object
 9   Length of Stay                       object
 10  Type of Admission                    object
 11  Patient Disposition                  object
 12  Discharge Year                       int64
 13  CCSR Diagnosis Code                  object
 14  CCSR Diagnosis Description           object
 15  CCSR Procedure Code                  object
 16  CCSR Procedure Description           object
 17  APR DRG Code                         int64
 18  APR DRG Description                  object
 19  APR MDC Code                         int64
 20  APR MDC Description                  object
 21  APR Severity of Illness Code         int64
 22  APR Severity of Illness Description  object
 23  APR Risk of Mortality                object
 24  APR Medical Surgical Description     object
 25  Payment Typology 1                   object
 26  Payment Typology 2                   object
 27  Payment Typology 3                   object
 28  Total Charges                        float64
 29  Year                                 int64
dtypes: float64(2), int64(5), object(23)
memory usage: 989.3+ MB

In [ ]:
# Convert any remaining string Dtypes in sparcs_combined to objects:
for col in sparcs_combined.select_dtypes('string').columns:
  sparcs_combined[col] = sparcs_combined[col].astype('object')

In [ ]:
# Drop year column
sparcs_combined.drop(columns=['Year'], inplace=True)

In [ ]:
# Convert permanent facility id to object
sparcs_combined['Permanent Facility Id'] = sparcs_combined['Permanent Facility Id'].astype('object')

# Convert APR codes to objects
for col in ['APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code']:
  sparcs_combined[col] = sparcs_combined[col].astype('object')

In [ ]:
# Remove entries that are missing zip code values
sparcs_combined = sparcs_combined.dropna(subset=['Zip Code'])

In [ ]:
# Save new CSV of cleaned sparcs combined
sparcs_combined.to_csv('/content/drive/MyDrive/Sparcs_Datafiles/sparcs_combined_clean_v1.csv', index=False)

In [ ]:
# Create a function to create mapping dict for {Facility Id: Name, and all codes: descriptions}
import logging

# Set up basic logger
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger(__name__)

def create_all_code_mappings (df, code_desc_pairs, excel_output_path=None):
  """
  Creates a mapping dictionary for multiple code-description pairs,
  drops all description columns,
  logs progress and optionally exports to excel (one sheet per code/desc pair).

  Parameters
  ----------
  - df: pd.DataFrame
        DataFrame with code and description columns.
  - code_desc_pairs: list of tuples
        List of (code_column, description_column) pairs.
  - excel_output_path: str, optional
        Path to save the output Excel file.
  Returns
  ----------
  - tuple
        (mapping_dicts, updated_df)
  """

  df = df.copy()
  mapping_dicts = {}

  def process_single_mapping (df, code_col, desc_col):
    logger.info(f"Processing mapping: {code_col} -> {desc_col}")

    # Filter out empty of invalid entries
    valid_rows = df[(df[code_col].notna()) & (df[desc_col].notna()) & (df[code_col] != '')]

    # Create mapping dict
    mapping_dict = (
        valid_rows[[code_col, desc_col]]
        .drop_duplicates(subset=[code_col])
        .set_index(code_col)[desc_col]
        .to_dict()
    )

    # Drop description column
    df = df.drop(columns=[desc_col])

    logger.info(f"Mapping created: {len(mapping_dict)} unique codes")
    return mapping_dict, df

  # Process all code/description pairs
  for code_col, desc_col in code_desc_pairs:
    mapping_dict, df = process_single_mapping(df, code_col, desc_col)
    mapping_dicts[code_col] = mapping_dict

  # Export to excel if wanted, with sheet groupings by category
  if excel_output_path:
    logger.info(f"Exporting all mappings to Excel: {excel_output_path}")

    with pd.ExcelWriter(excel_output_path) as writer:
      for code_col, mapping in mapping_dicts.items():
        sheet_name = code_col.replace('code', '').strip().title()[:30]
        mapping_df = pd.DataFrame(list(mapping.items()), columns=['Code', 'Description'])
        mapping_df.to_excel(writer, sheet_name=sheet_name, index=False)

    logger.info("Excel export completed successfully")


  return mapping_dicts, df


# Using mapping_dicts function:
code_desc_pairs = [
    ("Permanent Facility Id", "Facility Name"),
    ("CCSR Diagnosis Code", "CCSR Diagnosis Description"),
    ("CCSR Procedure Code", "CCSR Procedure Description"),
    ("APR DRG Code", "APR DRG Description"),
    ("APR MDC Code", "APR MDC Description"),
    ("APR Severity of Illness Code", "APR Severity of Illness Description")
]

mappings, clean_df = create_all_code_mappings(
    df=sparcs_combined,
    code_desc_pairs=code_desc_pairs,
    excel_output_path='/content/sparcs_mappings.xlsx'
)

In [ ]:
sparcs_combined_clean_v1 = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/sparcs_combined_clean_v1.csv')

In [ ]:
sparcs_combined_clean_v1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238636 entries, 0 to 4238635
Data columns (total 23 columns):
 #   Column                            Dtype
---  ------                            -----
 0   Health Service Area               object
 1   Hospital County                   object
 2   Permanent Facility Id             float64
 3   Age Group                         object
 4   Zip Code                          object
 5   Gender                            object
 6   Race                              object
 7   Ethnicity                         object
 8   Length of Stay                    object
 9   Type of Admission                 object
 10  Patient Disposition               object
 11  Discharge Year                    int64
 12  CCSR Diagnosis Code               object
 13  CCSR Procedure Code               object
 14  APR DRG Code                      int64
 15  APR MDC Code                      int64
 16  APR Severity of Illness Code      int64
 17  APR Risk of Mortality             object
 18  APR Medical Surgical Description  object
 19  Payment Typology 1                object
 20  Payment Typology 2                object
 21  Payment Typology 3                object
 22  Total Charges                     float64
dtypes: float64(2), int64(4), object(17)
memory usage: 743.8+ MB

#**Change Reporting of Payment Typology Columns**

In [ ]:
# Get all unique values reported in Payment typology columns
for col in ['Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3']:
  print(f"Unique values in {col}:")
  print(sparcs_combined_clean_v1[col].dropna().unique())
  print("\n")

Unique values in Payment Typology 1:
['Medicaid' 'Medicare' 'Private Health Insurance' 'Self-Pay'
 'Blue Cross/Blue Shield' 'Miscellaneous/Other' 'Federal/State/Local/VA'
 'Department of Corrections' 'Managed Care, Unspecified']


Unique values in Payment Typology 2:
['Medicaid' 'Blue Cross/Blue Shield' 'Private Health Insurance'
 'Federal/State/Local/VA' 'Medicare' 'Self-Pay' 'Miscellaneous/Other'
 'Managed Care, Unspecified' 'Department of Corrections']


Unique values in Payment Typology 3:
['Medicaid' 'Federal/State/Local/VA' 'Self-Pay' 'Medicare'
 'Private Health Insurance' 'Blue Cross/Blue Shield'
 'Managed Care, Unspecified' 'Miscellaneous/Other'
 'Department of Corrections']

In [ ]:
# Get value counts in payment typology columns
for col in ['Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3']:
  print(f"Value Counts for {col}:")
  print(sparcs_combined_clean_v1[col].value_counts(dropna=False))
  print("\n")

Value Counts for Payment Typology 1:
Payment Typology 1
Medicare                     1775903
Medicaid                     1251502
Private Health Insurance      601530
Blue Cross/Blue Shield        403119
Self-Pay                       61229
Managed Care, Unspecified      57198
Miscellaneous/Other            44160
Federal/State/Local/VA         40935
Department of Corrections       2834
NaN                              226
Name: count, dtype: int64


Value Counts for Payment Typology 2:
Payment Typology 2
NaN                          2264587
Medicaid                      826762
Medicare                      333777
Private Health Insurance      297494
Self-Pay                      255811
Blue Cross/Blue Shield        212895
Federal/State/Local/VA         24850
Managed Care, Unspecified      11150
Miscellaneous/Other            11124
Department of Corrections        186
Name: count, dtype: int64


Value Counts for Payment Typology 3:
Payment Typology 3
NaN                          3723609
Self-Pay                      282317
Medicaid                      138418
Private Health Insurance       38263
Blue Cross/Blue Shield         27034
Medicare                       23141
Federal/State/Local/VA          4202
Managed Care, Unspecified       1094
Miscellaneous/Other              517
Department of Corrections         41
Name: count, dtype: int64

In [ ]:
# Define a function to change payment typology columns to binary values
def encode_payment_typologies(df, save_path="sparcs_cleaned_v2.csv"):
  """
  Transform payment typology columns into binary indicator features and returns
  new dataframe, retaining the original.

  - Converts the three categorical payment typology columns
    ('Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3')
    into a set of binary columns.
  - Adds a numerical feature showing how many payers are present per row.
  - Deletes the original columns.
  - Saves a new cleaned dataframe to a CSV file.

  Parameters:
  - df: pd.DataFrame
      Input DataFrame with payment typology columns.

  - save_path: str, optional (default = "sparcs_cleaned_v2.csv")
      Path to save the new cleaned DataFrame.

  Returns:
  - df_cleaned: pd.DataFrame
      DataFrame with binary payer columns and a 'num_payers' feature and
      original columns dropped.

  """

  # Create a copy df so original is unchanged
  df_cleaned = df.copy()

  # Identify payment typology columns
  payment_cols = ['Payment Typology 1', 'Payment Typology 2', 'Payment Typology 3']

  # Get all unique payer types across all three columns
  unique_payers = pd.concat([df_cleaned[col] for col in payment_cols]).dropna().unique()

  # Create binary indicator for each unique payer type
  for payer in unique_payers:
    # Mark 1 if payer appears in any of the three payment typology columns, else mark 0
    df_cleaned[payer] = df_cleaned[payment_cols].eq(payer).any(axis=1).astype(int)

  # Add a feature counting how many payment typology fields are filled
  df_cleaned['Number of Payment Typologies'] = df_cleaned[payment_cols].notna().sum(axis=1)

  # Drop the original payment typology columns
  df_cleaned = df_cleaned.drop(columns=payment_cols)

  # Save the cleaned Dataframe as CSV
  df_cleaned.to_csv(save_path, index=False)

  return df_cleaned

In [ ]:
# Payment typology function usage
sparcs_cleaned_v2 = encode_payment_typologies(
    df=sparcs_combined_clean_v1)

In [16]:
# Load sparcs_cleaned_v2
sparcs_cleaned_v2 = pd.read_csv('/content/drive/MyDrive/Sparcs_Datafiles/sparcs_cleaned_v2.csv')

In [ ]:
print(sparcs_cleaned_v2.columns)

Index(['Health Service Area', 'Hospital County', 'Permanent Facility Id',
       'Age Group', 'Zip Code', 'Gender', 'Race', 'Ethnicity',
       'Length of Stay', 'Type of Admission', 'Patient Disposition',
       'Discharge Year', 'CCSR Diagnosis Code', 'CCSR Procedure Code',
       'APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code',
       'APR Risk of Mortality', 'APR Medical Surgical Description',
       'Total Charges', 'Medicaid', 'Medicare', 'Private Health Insurance',
       'Self-Pay', 'Blue Cross/Blue Shield', 'Miscellaneous/Other',
       'Federal/State/Local/VA', 'Department of Corrections',
       'Managed Care, Unspecified', 'Number of Payment Typologies'],
      dtype='object')

In [17]:
sparcs_cleaned_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238636 entries, 0 to 4238635
Data columns (total 30 columns):
 #   Column                            Dtype
---  ------                            -----
 0   Health Service Area               object
 1   Hospital County                   object
 2   Permanent Facility Id             float64
 3   Age Group                         object
 4   Zip Code                          object
 5   Gender                            object
 6   Race                              object
 7   Ethnicity                         object
 8   Length of Stay                    object
 9   Type of Admission                 object
 10  Patient Disposition               object
 11  Discharge Year                    int64
 12  CCSR Diagnosis Code               object
 13  CCSR Procedure Code               object
 14  APR DRG Code                      int64
 15  APR MDC Code                      int64
 16  APR Severity of Illness Code      int64
 17  APR Risk of Mortality             object
 18  APR Medical Surgical Description  object
 19  Total Charges                     float64
 20  Medicaid                          int64
 21  Medicare                          int64
 22  Private Health Insurance          int64
 23  Self-Pay                          int64
 24  Blue Cross/Blue Shield            int64
 25  Miscellaneous/Other               int64
 26  Federal/State/Local/VA            int64
 27  Department of Corrections         int64
 28  Managed Care, Unspecified         int64
 29  Number of Payment Typologies      int64
dtypes: float64(2), int64(14), object(14)
memory usage: 970.1+ MB

In [43]:
# Convert dtypes to ensure feature represented appropriately:
# Facility Id float -> object
sparcs_cleaned_v2['Permanent Facility Id'] = (
    sparcs_cleaned_v2['Permanent Facility Id']
    .astype('int')
    .astype('object')
)

# Convert APR codes int64 -> object
for col in ['APR DRG Code', 'APR MDC Code', 'APR Severity of Illness Code']:
  sparcs_cleaned_v2[col] = sparcs_cleaned_v2[col].astype('object')

In [21]:
# Check value counts for length of stay
pd.set_option('display.max_rows', None)

los_counts = sparcs_cleaned_v2['Length of Stay'].value_counts()
print(los_counts)

pd.reset_option('display.max_rows')

Length of Stay
2      904773
1      754283
3      644362
4      412965
5      288935
6      215594
7      171264
8      129534
9       99014
10      79606
11      66497
12      54736
13      49753
14      46026
15      36509
16      28905
17      24209
18      20741
19      18209
20      17005
21      16797
22      13398
23      11174
28      10866
24       9708
25       8753
27       8106
26       7866
29       6143
30       5166
31       4656
120      4452
32       4264
33       3876
34       3775
35       3650
36       3106
37       2696
38       2456
39       2295
42       2286
41       2210
40       2209
43       1927
44       1673
45       1614
46       1435
48       1412
47       1406
49       1365
50       1176
51       1125
53       1007
52       1005
56        933
55        912
54        890
57        806
58        767
61        678
63        674
59        663
62        657
60        643
64        577
70        509
65        485
69        484
66        455
68        450
72        436
71        429
67        411
77        404
73        370
76        363
78        347
74        346
75        339
79        304
83        283
84        280
82        272
80        252
85        248
81        239
91        225
87        219
90        205
89        203
86        198
92        187
95        183
88        178
97        172
93        172
98        170
94        154
96        148
104       148
99        145
106       144
100       137
105       131
101       129
102       129
103       123
107       112
110       110
111       109
114       104
112       103
109       100
113       100
108        96
119        94
118        92
116        83
115        80
117        74
Name: count, dtype: int64

In [20]:
# Convert LOS dtype to string for standardizing reporting
sparcs_cleaned_v2['Length of Stay'] = sparcs_cleaned_v2['Length of Stay'].astype('string')

# Convert any 120+ LOS values to 120 for ML
sparcs_cleaned_v2['Length of Stay'] = sparcs_cleaned_v2['Length of Stay'].apply(lambda x: '120' if str(x).startswith('120') else x)

In [38]:
sparcs_cleaned_v2.nunique()

Health Service Area                       8
Hospital County                          58
Permanent Facility Id                   209
Age Group                                 5
Zip Code                                 50
Gender                                    3
Race                                      4
Ethnicity                                 4
Length of Stay                          120
Type of Admission                         6
Patient Disposition                      19
Discharge Year                            2
CCSR Diagnosis Code                     479
CCSR Procedure Code                     319
APR DRG Code                            330
APR MDC Code                             25
APR Severity of Illness Code              5
APR Risk of Mortality                     5
APR Medical Surgical Description          3
Total Charges                       3446729
Medicaid                                  2
Medicare                                  2
Private Health Insurance                  2
Self-Pay                                  2
Blue Cross/Blue Shield                    2
Miscellaneous/Other                       2
Federal/State/Local/VA                    2
Department of Corrections                 2
Managed Care, Unspecified                 2
Number of Payment Typologies              4
dtype: int64

In [33]:
# Convert LOS to integer
sparcs_cleaned_v2['Length of Stay'] = sparcs_cleaned_v2['Length of Stay'].astype('int')

In [44]:
sparcs_cleaned_v2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238636 entries, 0 to 4238635
Data columns (total 30 columns):
 #   Column                            Dtype
---  ------                            -----
 0   Health Service Area               object
 1   Hospital County                   object
 2   Permanent Facility Id             object
 3   Age Group                         object
 4   Zip Code                          object
 5   Gender                            object
 6   Race                              object
 7   Ethnicity                         object
 8   Length of Stay                    int64
 9   Type of Admission                 object
 10  Patient Disposition               object
 11  Discharge Year                    int64
 12  CCSR Diagnosis Code               object
 13  CCSR Procedure Code               object
 14  APR DRG Code                      object
 15  APR MDC Code                      object
 16  APR Severity of Illness Code      object
 17  APR Risk of Mortality             object
 18  APR Medical Surgical Description  object
 19  Total Charges                     float64
 20  Medicaid                          int64
 21  Medicare                          int64
 22  Private Health Insurance          int64
 23  Self-Pay                          int64
 24  Blue Cross/Blue Shield            int64
 25  Miscellaneous/Other               int64
 26  Federal/State/Local/VA            int64
 27  Department of Corrections         int64
 28  Managed Care, Unspecified         int64
 29  Number of Payment Typologies      int64
dtypes: float64(1), int64(12), object(17)
memory usage: 970.1+ MB

In [45]:
sparcs_cleaned_v2.head()

,Health Service Area,Hospital County,Permanent Facility Id,Age Group,Zip Code,Gender,Race,Ethnicity,Length of Stay,Type of Admission,...,Medicaid,Medicare,Private Health Insurance,Self-Pay,Blue Cross/Blue Shield,Miscellaneous/Other,Federal/State/Local/VA,Department of Corrections,"Managed Care, Unspecified",Number of Payment Typologies
0,New York City,Bronx,3058,50-69,104,F,Other Race,Spanish/Hispanic,1,Emergency,...,1,0,0,0,0,0,0,0,0,1
1,New York City,Bronx,1168,30-49,104,M,Black/African American,Not Span/Hispanic,4,Emergency,...,1,0,0,0,0,0,0,0,0,1
2,New York City,Bronx,3058,50-69,104,M,Other Race,Not Span/Hispanic,4,Emergency,...,1,1,0,0,0,0,0,0,0,2
3,New York City,Bronx,1169,18-29,104,M,Black/African American,Not Span/Hispanic,5,Emergency,...,1,0,0,0,0,0,0,0,0,1
4,New York City,Bronx,1169,50-69,104,F,Other Race,Spanish/Hispanic,3,Emergency,...,1,1,0,0,0,0,0,0,0,2

In [46]:
# Save changes to sparcs_cleaned_v2 as new CSV: sparcs_cleaned_v3
sparcs_cleaned_v2.to_csv('/content/drive/MyDrive/Sparcs_Datafiles/sparcs_cleaned_v3.csv', index=False)

#**Handle Missing Values, Create Mapping dictionary for Code/Descriptions and Facility Id/Facility Name**

In [ ]:
#Check for missing values, the % missing and display as a table
missing_data = []
for col in sparcs_cleaned_v3.columns:
  missing_values = sparcs_cleaned_v3[col].isnull().sum()
  missing_percent = (missing_values / len(sparcs_cleaned_v3) * 100).round(2)
  missing_data.append({'Column': col, 'Missing Values': missing_values, 'Missing %': missing_percent})

missing_table = pd.DataFrame(missing_data)
display(missing_table)

#Statistical Summary and Visualizing Outliers

In [ ]:
#Generate plots for outliers

In [ ]:
#Remove numerical outliers using IQR method?

In [ ]:
#Figure out how to remove categorical outliers

#Correlation Analysis

In [ ]:
import matplotlib.pyplot as plt

unknown_counts = sparcs_cleaned_v3.apply(lambda col: (col == 'Unknown').sum())
unknown_percents = unknown_counts / len(sparcs_cleaned_v3) * 100

plt.figure(figsize=(10, 6))
unknown_percents.sort_values(ascending=True).plot(kind='barh')
plt.xlabel('Percentage of Unknown Values')
plt.ylabel('Column Name')
plt.title('Percentage of Unknown Values in Each Column')
plt.show()